version: '3.8'

services:
  vertica_ce:
    container_name: vertica_ce
    image: vertica/vertica-ce:10.1.1-0
    environment:
      - APP_DB_USER=vertica
      - APP_DB_PASSWORD=vertica
    ports:
        - 5433:5433
        - 5444:5444
    volumes:
      - vertica-data:/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  vertica-data:
